#!/usr/bin/env node
/**
 * gen-tools.mjs — F39
 *
 * Lit ${NUXT_PUBLIC_API_BASE}/openapi.json (par défaut http://localhost:8010/openapi.json),
 * filtre les schémas marqués `x-tool: true` et produit un fichier TypeScript par tool dans
 * frontend/app/types/tools/. Génère également un index.ts qui re-exporte la union
 * `ToolInstruction` / `ToolResponse`.
 *
 * Usage :
 *   node scripts/gen-tools.mjs           # échec si l'API n'est pas joignable
 *   node scripts/gen-tools.mjs --soft    # avertit puis sort 0 (utilisé en pre-build CI/dev)
 *
 * Le script reste minimal : il s'appuie sur la convention OpenAPI Pydantic du backend (F15)
 * et n'essaie pas de faire de la generation zod complète (le contrat Pydantic = source de
 * vérité, le frontend valide à l'ouverture via les schémas zod manuels du wrapper).
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import process from 'node:process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TARGET_DIR = resolve(__dirname, '../app/types/tools')
const SOFT_MODE = process.argv.includes('--soft')
const API_BASE = process.env.NUXT_PUBLIC_API_BASE ?? 'http://localhost:8010'

const KNOWN_TOOLS = [
  'ask_qcu',
  'ask_qcm',
  'ask_yes_no',
  'ask_select',
  'ask_number',
  'ask_date',
  'ask_date_range',
  'ask_rating',
  'ask_file_upload',
  'show_form',
  'show_summary_card',
]

async function fetchOpenApi() {
  const url = `${API_BASE.replace(/\/$/, '')}/openapi.json`
  const res = await fetch(url, { headers: { accept: 'application/json' } })
  if (!res.ok) throw new Error(`HTTP ${res.status} on ${url}`)
  return res.json()
}

function pickToolSchemas(spec) {
  const schemas = spec?.components?.schemas ?? {}
  const tools = {}
  for (const [name, schema] of Object.entries(schemas)) {
    if (schema && (schema['x-tool'] === true || KNOWN_TOOLS.includes(name))) {
      tools[name] = schema
    }
  }
  return tools
}

function header(name) {
  return [
    '// AUTO-GENERATED by scripts/gen-tools.mjs — do not edit by hand.',
    `// Source: ${API_BASE}/openapi.json (component schema "${name}").`,
    '// Régénérer avec `pnpm gen:tools`.',
    '',
  ].join('\n')
}

function emitToolFile(name, schema) {
  const json = JSON.stringify(schema, null, 2)
  return `${header(name)}export const ${name}Schema = ${json} as const\nexport type ${name}Schema = typeof ${name}Schema\n`
}

function emitIndex(toolNames) {
  const lines = [
    '// AUTO-GENERATED by scripts/gen-tools.mjs — do not edit by hand.',
    '',
    ...toolNames.map((n) => `export * from './${n}'`),
    '',
    `export const TOOL_NAMES = ${JSON.stringify(toolNames)} as const`,
    'export type ToolName = (typeof TOOL_NAMES)[number]',
    '',
  ]
  return lines.join('\n')
}

async function emitFallbackIndex(reason) {
  await mkdir(TARGET_DIR, { recursive: true })
  const content = [
    '// AUTO-GENERATED fallback (backend OpenAPI unreachable).',
    `// Reason: ${reason}`,
    '// Les wrappers utilisent les schémas zod manuels du contrat tool-payloads.md.',
    '',
    `export const TOOL_NAMES = ${JSON.stringify(KNOWN_TOOLS)} as const`,
    'export type ToolName = (typeof TOOL_NAMES)[number]',
    '',
  ].join('\n')
  await writeFile(resolve(TARGET_DIR, 'index.ts'), content, 'utf8')
}

async function main() {
  let spec
  try {
    spec = await fetchOpenApi()
  } catch (err) {
    const msg = err?.message ?? String(err)
    if (SOFT_MODE) {
      // eslint-disable-next-line no-console
      console.warn(`[gen-tools] OpenAPI introuvable (${msg}) — fallback index.ts généré.`)
      await emitFallbackIndex(msg)
      return
    }
    throw err
  }

  const tools = pickToolSchemas(spec)
  const toolNames = Object.keys(tools).sort()
  await mkdir(TARGET_DIR, { recursive: true })

  if (toolNames.length === 0) {
    await emitFallbackIndex('aucun schéma marqué x-tool dans /openapi.json')
    // eslint-disable-next-line no-console
    console.warn('[gen-tools] Aucun tool détecté ; fallback index.ts écrit.')
    return
  }

  await Promise.all(
    toolNames.map((name) => writeFile(resolve(TARGET_DIR, `${name}.ts`), emitToolFile(name, tools[name]), 'utf8')),
  )
  await writeFile(resolve(TARGET_DIR, 'index.ts'), emitIndex(toolNames), 'utf8')
  // eslint-disable-next-line no-console
  console.log(`[gen-tools] ${toolNames.length} tool(s) générés dans ${TARGET_DIR}`)
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('[gen-tools] échec :', err?.message ?? err)
  process.exit(1)
})
